// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace StockPlay.Web {
	
	
	public partial class User_CreateOrder {
		
		protected System.Web.UI.WebControls.Content Content1;
		
		protected System.Web.UI.WebControls.Content Content2;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl Security;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl Quote;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl Cash;
		
		protected System.Web.UI.WebControls.Literal SoortOrder;
		
		protected System.Web.UI.WebControls.DropDownList OrderType;
		
		protected System.Web.UI.WebControls.Literal lblPara4;
		
		protected System.Web.UI.WebControls.TextBox txtAmount;
		
		protected System.Web.UI.WebControls.Literal lblMultiply;
		
		protected System.Web.UI.WebControls.TextBox txtQuote;
		
		protected System.Web.UI.WebControls.Literal lblEquals;
		
		protected System.Web.UI.WebControls.Label Total;
		
		protected System.Web.UI.WebControls.Literal lblOnderLimiet;
		
		protected System.Web.UI.WebControls.TextBox txtOnderLimiet;
		
		protected System.Web.UI.WebControls.Literal lblBovenLimiet;
		
		protected System.Web.UI.WebControls.TextBox txtBovenLimiet;
		
		protected System.Web.UI.WebControls.Literal lblBonuspunten;
		
		protected System.Web.UI.WebControls.TextBox txtBonuspunten;
		
		protected System.Web.UI.WebControls.RangeValidator RangeValidator1;
		
		protected System.Web.UI.WebControls.RangeValidator RangeValidator2;
		
		protected System.Web.UI.WebControls.Label ErrorLabel;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl Notification;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl NewBalance;
		
		protected System.Web.UI.WebControls.Button btnConfirm;
		
		protected System.Web.UI.WebControls.Button btnContinue;
		
		protected System.Web.UI.WebControls.Button btnCancel;
	}
}
