// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace StockPlay.Web {
	
	
	public partial class User_OrdersOverview {
		
		protected System.Web.UI.WebControls.Content Content1;
		
		protected System.Web.UI.WebControls.Content Content2;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl DeleteMessage;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl OrderId;
		
		protected System.Web.UI.WebControls.Literal Literal1;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl SecurityID;
		
		protected System.Web.UI.WebControls.Button btnConfirm;
		
		protected System.Web.UI.WebControls.Button btnCancel;
		
		protected System.Web.UI.WebControls.GridView OrdersGridview;
	}
}
