// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace StockPlay.Web {
	
	
	public partial class User_Overview {
		
		protected System.Web.UI.WebControls.Content Content1;
		
		protected System.Web.UI.WebControls.Content Content2;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl Username;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl Lastname;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl Firstname;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl Email;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl Balance;
		
		protected System.Web.UI.HtmlControls.HtmlTable AccountUpdate;
		
		protected System.Web.UI.WebControls.TextBox OldPassword;
		
		protected System.Web.UI.WebControls.RequiredFieldValidator PasswordRequired;
		
		protected System.Web.UI.WebControls.TextBox NewPassword;
		
		protected System.Web.UI.WebControls.RequiredFieldValidator NewPasswordRequired;
		
		protected System.Web.UI.WebControls.TextBox ConfirmPassword;
		
		protected System.Web.UI.WebControls.RequiredFieldValidator ConfirmPasswordRequired;
		
		protected System.Web.UI.WebControls.CompareValidator CompareValidator;
		
		protected System.Web.UI.WebControls.TextBox txtLastname;
		
		protected System.Web.UI.WebControls.TextBox txtFirstname;
		
		protected System.Web.UI.WebControls.TextBox txtEmail;
		
		protected System.Web.UI.WebControls.RegularExpressionValidator RegularExpressionValidator1;
		
		protected System.Web.UI.WebControls.Button btnUpdate;
		
		protected System.Web.UI.WebControls.Label ErrorLabel;
	}
}
