// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace StockPlay.Web {
	
	
	public partial class User_Portfolio {
		
		protected System.Web.UI.WebControls.Content Content1;
		
		protected System.Web.UI.WebControls.Content Content2;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl SellMessage;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl SecurityName;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl Price;
		
		protected System.Web.UI.WebControls.Literal Literal1;
		
		protected System.Web.UI.WebControls.Literal SoortOrder;
		
		protected System.Web.UI.WebControls.DropDownList OrderType;
		
		protected System.Web.UI.WebControls.Literal lblAantal;
		
		protected System.Web.UI.WebControls.TextBox txtAmount;
		
		protected System.Web.UI.WebControls.Literal lblStreep;
		
		protected System.Web.UI.WebControls.TextBox txtTotalAmount;
		
		protected System.Web.UI.WebControls.RangeValidator txtAmountValidator;
		
		protected System.Web.UI.WebControls.Literal lblVraagprijs;
		
		protected System.Web.UI.WebControls.TextBox txtPrice;
		
		protected System.Web.UI.WebControls.RangeValidator txtPriceValidator;
		
		protected System.Web.UI.WebControls.Literal lblOnderLimiet;
		
		protected System.Web.UI.WebControls.TextBox txtOnderLimiet;
		
		protected System.Web.UI.WebControls.Literal lblBovenLimiet;
		
		protected System.Web.UI.WebControls.TextBox txtBovenLimiet;
		
		protected System.Web.UI.WebControls.Literal lblBonuspunten;
		
		protected System.Web.UI.WebControls.TextBox txtBonuspunten;
		
		protected System.Web.UI.WebControls.Button btnConfirm;
		
		protected System.Web.UI.WebControls.Button btnCancel;
		
		protected System.Web.UI.WebControls.GridView PortfolioGridview;
	}
}
