#!/usr/bin/env perl

################################################################################
# Configuration
#

# Packages
use StockPlay;
use StockPlay::Factory;
use Date::Manip;
use DateTime::Format::DateManip;

# Write nicely
use warnings;
use strict;



################################################################################
# Main
#

#
# Setup
#

my $stockplay = new StockPlay(app => "test");
my $factory = $stockplay->getFactory();
my $logger = $stockplay->getLogger();


#
# Test

$logger->debug("testing");

my $start = DateTime::Format::DateManip->parse_datetime(ParseDate("1 month ago"));
my $end = DateTime::Format::DateManip->parse_datetime(ParseDate("today"));

my $exchange = (grep { $_->symbol eq "BSE" } $factory->getExchanges())[0] or die();
my $security = (grep { $_->isin eq "BE0003755692" } $factory->getSecurities($exchange))[0] or die();
my @quotes = $factory->getQuotes($start, $end, $security, 60*60*24);

print "Quotes:\n\t", join("\n\t", map { $_->time->dmy . " " . $_->time->hms } sort { DateTime->compare($a->time, $b->time) } @quotes), "\n";

exit(0);



################################################################################
# Routines
#

__END__



################################################################################
# Documentation
#

=pod

=head1 NAME

stockplay-test - StockPlay test client.

=head1 DESCRIPTION

This client is used to quickly verify backend functionality.

=head1 COPYRIGHT

Copyright 2010 The StockPlay development team as listed in the AUTHORS file.

This software is free software; you can redistribute it and/or modify it under
the terms of the GNU General Public Licence (GPL) as published by the
Free Software Foundation (FSF).

The full text of the license can be found in the
LICENSE file included with this module.

=cut
