#!/usr/bin/env perl

################################################################################
# Configuration
#

# Packages
use StockPlay::Logger;
use StockPlay::Factory;
use StockPlay::AI::Manager;

# Write nicely
use warnings;
use strict;



################################################################################
# Main
#

# Get a logger
StockPlay::Logger->setup("ai");
my $logger = StockPlay::Logger->logger;
$logger->info("bootstrapping ai");

# Load the factory
$logger->debug("loading factory");
my $factory = new StockPlay::Factory();

# Load the manager
$logger->debug("loading manager");
my $manager = new StockPlay::AI::Manager(
	factory	=> $factory
);
$manager->run();

exit(0);

__END__



################################################################################
# Documentation
#

=pod

=head1 NAME

stockplay-scraper - Scraper component of StockPlay

=head1 SYNOPSIS

=head1 COPYRIGHT

Copyright 2010 The StockPlay development team as listed in the AUTHORS file.

This software is free software; you can redistribute it and/or modify it under
the terms of the GNU General Public Licence (GPL) as published by the
Free Software Foundation (FSF).

The full text of the license can be found in the
LICENSE file included with this module.

=cut
