#!/usr/bin/env perl

################################################################################
# Configuration
#

# Packages
use StockPlay;
use StockPlay::Scraper;

# Write nicely
use warnings;
use strict;



################################################################################
# Main
#

# Get a logger
StockPlay::Logger->setup("scraper");
my $logger = StockPlay::Logger->logger;
$logger->info("bootstrapping scraper");

my $stockplay = new StockPlay();
my $factory = $stockplay->getFactory();
my $scraper = $stockplay->getScraper();

$scraper->run();

exit(0);

__END__



################################################################################
# Documentation
#

=pod

=head1 NAME

stockplay-scraper - Scraper component of StockPlay

=head1 DESCRIPTION

This part of the StockPlay framework is responsible for gathering realtime
(or pseudo-realtime) data from continuus resources.

=head1 COPYRIGHT

Copyright 2010 The StockPlay development team as listed in the AUTHORS file.

This software is free software; you can redistribute it and/or modify it under
the terms of the GNU General Public Licence (GPL) as published by the
Free Software Foundation (FSF).

The full text of the license can be found in the
LICENSE file included with this module.

=cut
