#!/usr/bin/env perl

################################################################################
# Configuration
#

# Packages
use StockPlay;
use StockPlay::AI;

# Write nicely
use warnings;
use strict;



################################################################################
# Main
#

my $stockplay = new StockPlay(app => "ai");
my $factory = $stockplay->getFactory();
my $ai = $stockplay->getAI();
my $logger = $stockplay->getLogger();

$ai->run();

exit(0);

__END__



################################################################################
# Documentation
#

=pod

=head1 NAME

stockplay-ai - Artificial player intelligence

=head1 DESCRIPTION

This script emulates the behaviour of an ordinary player using a set of
artificial intelligence technologies. It aims at maximizing the return profits
of the investment.

=head1 COPYRIGHT

Copyright 2010 The StockPlay development team as listed in the AUTHORS file.

This software is free software; you can redistribute it and/or modify it under
the terms of the GNU General Public Licence (GPL) as published by the
Free Software Foundation (FSF).

The full text of the license can be found in the
LICENSE file included with this module.

=cut
