#!/usr/bin/env perl

################################################################################
# Configuration
#

# Packages
use StockPlay::Factory;
use StockPlay::Exchange;
use StockPlay::Index;
use StockPlay::Security;

# Write nicely
use warnings;
use strict;



################################################################################
# Main
#

#
# Setup
#

# Get a logger
StockPlay::Logger->setup("test");
my $logger = StockPlay::Logger->logger;
$logger->info("loading test client");

# Load the factory
$logger->debug("loading factory");
my $factory = new StockPlay::Factory();


#
# Test
#

$logger->info("fetching dataset");
my @exchanges = $factory->buildExchanges();

print "- Found exchanges:\n";
foreach my $exchange (@exchanges) {
	print "\t" . $exchange->name . "\n";
}

exit(0);



################################################################################
# Routines
#

__END__



################################################################################
# Documentation
#

=pod

=head1 NAME

stockplay-test - StockPlay test client.

=head1 SYNOPSIS

=head1 COPYRIGHT

Copyright 2010 The StockPlay development team as listed in the AUTHORS file.

This software is free software; you can redistribute it and/or modify it under
the terms of the GNU General Public Licence (GPL) as published by the
Free Software Foundation (FSF).

The full text of the license can be found in the
LICENSE file included with this module.

=cut
