#!/usr/bin/env perl

################################################################################
# Configuration
#

# XXX: library location
use lib '../lib';

# Packages
use StockPlay::Factory;
use StockPlay::Exchange;
use StockPlay::Index;
use StockPlay::Security;

# Write nicely
use warnings;
use strict;


################################################################################
# Main
#

# Load the factory
print "- Setting up factory\n";
my $factory = new StockPlay::Factory();

print "- Building hierarchy\n";
my @exchanges = $factory->buildExchanges();

exit(0);

################################################################################
# Routines
#

__END__

################################################################################
# Documentation
#

=pod

=head1 NAME

stockplay-test - StockPlay test client.

=head1 SYNOPSIS

=head1 COPYRIGHT

Copyright 2010 The StockPlay development team as listed in the AUTHORS file.

This software is free software; you can redistribute it and/or modify it under
the terms of the GNU General Public Licence (GPL) as published by the
Free Software Foundation (FSF).

The full text of the license can be found in the
LICENSE file included with this module.

=cut
