// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace StockPlay.Web {
	
	
	public partial class Register {
		
		protected System.Web.UI.WebControls.Content Content1;
		
		protected System.Web.UI.WebControls.Content Content2;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl FinishRegistration;
		
		protected System.Web.UI.HtmlControls.HtmlTable TableRegister;
		
		protected System.Web.UI.WebControls.TextBox UserName;
		
		protected System.Web.UI.WebControls.RequiredFieldValidator NicknameRequired;
		
		protected System.Web.UI.WebControls.TextBox Password;
		
		protected System.Web.UI.WebControls.RequiredFieldValidator PasswordRequired;
		
		protected System.Web.UI.WebControls.TextBox txtPasswordConfirm;
		
		protected System.Web.UI.WebControls.CompareValidator PasswordCompare;
		
		protected System.Web.UI.WebControls.TextBox txtLastname;
		
		protected System.Web.UI.WebControls.RequiredFieldValidator LastnameRequired;
		
		protected System.Web.UI.WebControls.TextBox txtFirstname;
		
		protected System.Web.UI.WebControls.RequiredFieldValidator FirstnameRequired;
		
		protected System.Web.UI.WebControls.TextBox Email;
		
		protected System.Web.UI.WebControls.RequiredFieldValidator EmailRequired;
		
		protected System.Web.UI.WebControls.RegularExpressionValidator RegularExpressionValidator1;
		
		protected System.Web.UI.WebControls.Button btnRegister;
		
		protected System.Web.UI.WebControls.Button btnCancel;
		
		protected System.Web.UI.WebControls.Label ErrorLabel;
	}
}
