// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace StockPlay.Web {
	
	
	public partial class SecurityDetail {
		
		protected System.Web.UI.WebControls.Content Content1;
		
		protected System.Web.UI.WebControls.Content Content2;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl Name;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl Value;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl Change;
		
		protected System.Web.UI.WebControls.HyperLink BuyHyperlink;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl Exchange;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl ISIN;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl Symbol;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl Open;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl High;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl Low;
		
		protected System.Web.UI.WebControls.GridView HistoryGridView;
	}
}
